{% set name = "backports.tarfile" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/backports_tarfile-{{ version }}.tar.gz
  sha256: d75e02c268746e1b8144c278978b6e98e85de6ad16f8e4b0844a154557eca991

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - setuptools-scm >=3.4.1
    - pip
    - backports
  run:
    - python >=3.8
    - backports

test:
  imports:
    - backports.tarfile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaraco/backports.tarfile
  summary: Backport of CPython tarfile module
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carlodri
